"""
api.py — FastAPI inference server for the Chest X-Ray classifier.

Endpoints:
  POST /predict        — Upload an image, get prediction + confidence
  GET  /health         — Health check
  GET  /docs           — Swagger UI (auto-generated by FastAPI)

Usage:
    uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload

Example curl:
    curl -X POST "http://localhost:8000/predict" \
         -H "accept: application/json" \
         -F "file=@path/to/xray.jpeg"
"""

import io
import base64
import time
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import JSONResponse
import albumentations as A
from albumentations.pytorch import ToTensorV2

from model import ChestXRayModel
from dataset import CLASS_NAMES, IMAGE_SIZE, MEAN, STD


# ─── Config ───────────────────────────────────────────────────────────────────
CKPT_PATH = Path("../outputs/best_model.pth")
THRESHOLD = 0.5   # P(pneumonia) threshold

# ─── App ──────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Chest X-Ray Classifier API",
    description="EfficientNetV2-S binary classifier: NORMAL vs PNEUMONIA",
    version="1.0.0",
)
from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── Global model (loaded at startup) ────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else
                      "mps" if torch.backends.mps.is_available() else "cpu")
model: ChestXRayModel = None


@app.on_event("startup")
def load_model():
    global model
    if not CKPT_PATH.exists():
        print(f"WARNING: Checkpoint not found at {CKPT_PATH}. /predict will fail.")
        return
    model = ChestXRayModel().to(device)
    ckpt  = torch.load(CKPT_PATH, map_location=device, weights_only=False)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()
    print(f"Model loaded from {CKPT_PATH} (epoch {ckpt['epoch']}, val AUC {ckpt['val_auc']:.4f})")


# ─── Transform ────────────────────────────────────────────────────────────────
_transform = A.Compose([
    A.Resize(IMAGE_SIZE, IMAGE_SIZE),
    A.Normalize(mean=MEAN, std=STD),
    ToTensorV2(),
])


def preprocess(image_bytes: bytes) -> torch.Tensor:
    image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    image_np = np.array(image)
    tensor = _transform(image=image_np)["image"]
    return tensor.unsqueeze(0).to(device)


# ─── Grad-CAM (lightweight inline version) ────────────────────────────────────
def get_gradcam_b64(image_tensor: torch.Tensor, class_idx: int) -> str:
    """Return a base64-encoded PNG of the Grad-CAM overlay."""
    image_tensor = image_tensor.clone().requires_grad_(True)

    activations, gradients = {}, {}

    def fwd_hook(m, inp, out):
        activations["feat"] = out

    def bwd_hook(m, gin, gout):
        gradients["feat"] = gout[0]

    target_layer = model.backbone.features[-1]
    h1 = target_layer.register_forward_hook(fwd_hook)
    h2 = target_layer.register_full_backward_hook(bwd_hook)

    logits = model(image_tensor)
    model.zero_grad()
    logits[0, class_idx].backward()

    h1.remove(); h2.remove()

    weights = gradients["feat"].mean(dim=(2, 3), keepdim=True)
    cam = (weights * activations["feat"]).sum(dim=1).squeeze()
    cam = F.relu(cam).detach().cpu().numpy()
    cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

    cam_resized = cv2.resize(cam, (IMAGE_SIZE, IMAGE_SIZE))
    heatmap = cv2.applyColorMap((cam_resized * 255).astype(np.uint8), cv2.COLORMAP_JET)
    heatmap_rgb = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB) / 255.0

    # Reconstruct original image (denorm)
    mean_np = np.array(MEAN); std_np = np.array(STD)
    orig = image_tensor.squeeze().detach().cpu().permute(1, 2, 0).numpy()
    orig = (orig * std_np + mean_np).clip(0, 1)

    overlay = (0.55 * orig + 0.45 * heatmap_rgb).clip(0, 1)
    overlay_uint8 = (overlay * 255).astype(np.uint8)

    _, buf = cv2.imencode(".png", cv2.cvtColor(overlay_uint8, cv2.COLOR_RGB2BGR))
    return base64.b64encode(buf.tobytes()).decode("utf-8")


# ─── Endpoints ────────────────────────────────────────────────────────────────
@app.get("/health")
def health():
    return {
        "status": "ok",
        "model_loaded": model is not None,
        "device": str(device),
    }


@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    if model is None:
        raise HTTPException(status_code=503, detail="Model not loaded — check checkpoint path")

    # Validate file type
    if file.content_type not in {"image/jpeg", "image/png", "image/jpg"}:
        raise HTTPException(status_code=400, detail="Only JPEG/PNG images are accepted")

    t0 = time.perf_counter()
    image_bytes = await file.read()

    try:
        tensor = preprocess(image_bytes)
    except Exception as e:
        raise HTTPException(status_code=422, detail=f"Image preprocessing failed: {e}")

    with torch.no_grad():
        logits = model(tensor)
        probs  = torch.softmax(logits, dim=1)[0].cpu().numpy()

    pred_idx  = int(probs.argmax())
    pneumonia_prob = float(probs[1])
    prediction = CLASS_NAMES[pred_idx]
    confidence = float(probs[pred_idx])
    latency_ms = (time.perf_counter() - t0) * 1000

    # Grad-CAM
    gradcam_b64 = get_gradcam_b64(tensor, class_idx=pred_idx)

    return JSONResponse({
        "prediction":     prediction,
        "confidence":     round(confidence, 4),
        "pneumonia_prob": round(pneumonia_prob, 4),
        "normal_prob":    round(float(probs[0]), 4),
        "threshold":      THRESHOLD,
        "latency_ms":     round(latency_ms, 2),
        "gradcam_png_b64": gradcam_b64,   # decode with base64 to display overlay
    })
